services:
  # Oracle XE 資料庫
  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: userms-oracle-xe
    environment:
      # 資料庫管理員密碼
      ORACLE_PWD: AdminPassword123
      # 資料庫字元集
      ORACLE_CHARACTERSET: AL32UTF8
      # 啟用 ArchiveLog 模式
      ORACLE_EDITION: xe
    ports:
      - "1521:1521"
      - "5500:5500"  # EM Express
    volumes:
      # 資料持久化
      - oracle_data:/opt/oracle/oradata
      # 初始化腳本
      - ./docker/oracle/init:/docker-entrypoint-initdb.d/startup
      # 自定義配置
      - ./docker/oracle/config:/opt/oracle/scripts/setup
    networks:
      - userms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/AdminPassword123@localhost:1521/XE", "as", "sysdba", "@/opt/oracle/checkdb.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  oracle_data:
    driver: local

networks:
  userms-network:
    driver: bridge