# 開發環境配置
spring:
  datasource:
    # 注意：Oracle 21c 使用 PDB 連線方式
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: userms_dev
    password: DevPassword123
    driver-class-name: oracle.jdbc.OracleDriver

    # 連線池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      pool-name: UserMS-HikariCP-Dev

  jpa:
    # 開發環境顯示 SQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 顯示綁定參數
        show_sql: true
        # 統計資訊
        generate_statistics: true

  # Flyway 配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    # schemas: userms_dev
    table: flyway_schema_history
    create-schemas: false

# p6spy SQL 監控配置（開發階段啟用）
# 如需啟用，將上方 datasource 配置改為：
# url: jdbc:p6spy:oracle:thin:@localhost:1521/XEPDB1
# driver-class-name: com.p6spy.engine.spy.P6SpyDriver

logging:
  level:
    com.userms: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    com.p6spy: INFO

# 開發環境 Actuator 完全開放
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always