# 用戶驗收測試環境配置
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: userms_uat
    password: UatPassword123
    driver-class-name: oracle.jdbc.OracleDriver

    # 連線池配置
    hikari:
      maximum-pool-size: 15
      minimum-idle: 8
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: UserMS-HikariCP-UAT

  jpa:
    # UAT 環境不顯示 SQL
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Flyway 配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    schemas: userms_uat
    table: flyway_schema_history

logging:
  level:
    com.userms: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

# UAT 環境限制 Actuator 端點
management:
  endpoints:
    web:
      exposure:
        include: health,info